### ISSUE TITLE
Event Sticker GitHub

### ISSUE THREAD

**Issue by SunDi3yansyah** [GitIndonesia/members#13]
Sticker yang diberikan dari pihak GitHub kurang lebih sebanyak 220.

Tolong berikan vote dibawah ini:

**1. 1 orang = 5 sticker**
**2. 1 orang = 10 sticker**

Cara votenya, silakan komentar dengan isi:
Jika memilih opsi 1
```
VOTE 1
```
Jika memilih opsi 2
```
VOTE 2
```
Sertakan alasannya.
Kurang dan lebih jumlah sticker silakan komentar.

STOK terbatas!
Oh ya 1 lagi, ini ada 20 jenis stiker :smile: 

> kita ingin nanti klo stiker sudah sampai di rumah masing-masing silakan selfi ya :smile: kita showcase ke staff github klo stiker sudah di bagikan ke member.

**Comment by eka-putra** [comment]
VOTE 1
Biar lebih banyak member yang kebagian stickernya.

**Comment by dfath** [comment]
VOTE 1
berbagi

**Comment by vcleapz** [comment]
VOTE 1
Gausah banyak2, biar semua kebagian :+1:  thanks mastah

**Comment by aris-kun** [comment]
VOTE 1
berbagi itu indah :+1:

**Comment by maulayyacyber** [comment]
VOTE 1 
Biar yang lain dapat mastah ^_^

**Comment by 404Ghost99** [comment]
vote 2 
mau pasang di kamar :v kowkowkowkwo

**Comment by tebe4rt** [comment]
VOTE 2
disini di bagi bagi lagi :v

**Comment by edorahayu** [comment]
VOTE 1
Biar lebih banyak yang kebagian....

**Comment by zhiephie** [comment]
> VOTE 1

**Comment by muhammad-ihsan** [comment]
VOTE 1

**Comment by zhiephie** [comment]
:package:

**Comment by enggaroff** [comment]
VOTE 1
biar yang lainnya juga dapet :)

**Comment by Zakisu** [comment]
VOTE 1

**Comment by NaufalHSyahputra** [comment]
VOTE 1 
Ga perlu banyak2 , kasihan yang lain juga pada mau

**Comment by ExcelOkta** [comment]
VOTE 1
Biar semua kebagian

**Comment by SunDi3yansyah** [comment]
**CLOSED**

Winner is option 1 :v: sok turis :smiling_imp:

**Comment by SunDi3yansyah** [comment]
Silakan yang mau stikernya, bisa di isi data masing-masing sebelum HABIS!

https://github.com/GitIndonesia/members/blob/master/README.md
https://github.com/GitIndonesia/members/blob/master/DETAILS.md

**Comment by hendrasyp** [comment]
VOTE 1 BIar semua kebagian Hahaha

**Comment by SunDi3yansyah** [comment]
@dikiaap yap, thanks suges nya

**Comment by SunDi3yansyah** [comment]
@dikiaap  https://github.com/GitIndonesia/members/commit/bbf3b590177f009b45a554f678e148fe92d77ab7

**Comment by SunDi3yansyah** [comment]
Mohon maaf, saya mengutamakan yang sudah bayar pengirimannya, jadi yang stikernya sudah habis tapi belum bayar silakan ganti jenis stikernya :+1: semua bagus kok :smile:

**Comment by SunDi3yansyah** [comment]
User disini yang sudah mengisi data tapi belum konfirmasi event stikernya

@abdilahrf (sudah mengisi stiker tapi belum konfirmasi)
@vcleapz
@andhikamaheva
@dyazincahya
@eka-putra (sudah mengisi stiker tapi belum konfirmasi)
@achmiral (sudah mengisi stiker tapi belum konfirmasi)

**Comment by padli** [comment]
VOTE 1
biar semua kebagian

**Comment by SunDi3yansyah** [comment]
iya vote nya sudah jelas, dibagi 5 stiker per orang 😄

Kamis, 04 Februari 2016, khoirul padli <notifications@github.com> menulis:

> VOTE 1
> biar semua kebagian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitIndonesia/members/issues/13#issuecomment-179745820>
> .
>


-- 
Dikirim dari iPhone
