### ISSUE TITLE
[REQUEST] Gitterim untuk GitIndonesia, kapan?

### ISSUE THREAD

**Issue by indrakaw** [GitIndonesia/members#54]
Maaf bila saya ajukan permintaan ini di repo member... Saya tidak tahu tempat lain untuk komunikasi dengan member @GitIndonesia. 

Seperti yang tertera di judul, saya request [Gitterim](https://gitter.im/) untuk organisasi ini. Agar bisa komunikasi dengan member Indonesia lain. Bisa?

Vote:
:+1: = Setuju
:-1: = Tidak setuju

Bila hasil positif, manajemen/pendaftaran ke Gitterim akan dipegang Admin/Mods GitIndonesia.

**Comment by dikiaap** [comment]
Masuk aja di gitter. Link (badges) nya udah ada di repo ini.

**Comment by indrakaw** [comment]
Oh. Salahku. :dizzy_face:
